### ISSUE TITLE
authorization for viewing video

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#1]
As a video viewer, I want to watch a video that has restricted access. As a video owner, I want to restrict access only to viewers who are members of a Moira list. 

When the viewer requests the embed code (HTML) to watch a video, the app will check to see that the viewer is a member of the appropriate group. If they are, it will return the embed code along with a signed cloudfront URL. The cloudfront URL will be time-limited to discourage sharing of the URL. 

If the viewer is not authorized, the app will return a 404 error.

**Comment by singingwolfboy** [comment]
Do we want a `401 Unauthorized` code, or a `404 Not Found` code? The more semantically correct thing to do would be a 401, but that reveals the presence of content at that URL. We could use 404 if unauthorized users shouldn't even know whether there is content or not. [(status codes on Wikipedia)](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors)

**Comment by pdpinch** [comment]
I'd prefer we return a 404 so we don't leak information about the existence of content. We should log the 401.

**Comment by singingwolfboy** [comment]
At this point in time, the app supports the following functionality:
* Selecting files from the Dropbox Chooser
* Streaming those files from Dropbox to an S3 bucket, with a progressbar
* Listing files that exist in the S3 bucket, with direct links to the files on CloudFront
* Generating signed CloudFront URLs for those files, so that users can download the files for a period of two hours

This requires the following configuration values to be set in the `.env` file:
* A Dropbox app key (the app secret is actually not used)
* An AWS access key and secret
* The name of the S3 bucket to use, and the ID of a CloudFront distribution that has already been configured to serve files from that S3 bucket
* An AWS private key, used to sign URLs for accessing private content in CloudFront

@blarghmatey and I have tried to figure out how to generate an AWS private key for signing URLs, but so far, we haven't been successful -- all the documentation we've found seems to be out of date. As a result, I haven't yet managed to successfully generate signed URLs for content on CloudFront. However, based on following [the documentation that I _have_ found about this process](http://boto3.readthedocs.io/en/stable/reference/services/cloudfront.html#generate-a-signed-url-for-amazon-cloudfront), this _should_ work once we plug in the private key. Theoretically.

**Comment by singingwolfboy** [comment]
Update: I found out how to generate CloudFront key pairs for my personal AWS account. On Monday, I'll work with Tobias to see how to do this on the AWS account for ODL.
![CloudFront key pair](https://cloud.githubusercontent.com/assets/132355/25314935/ddd79f20-281a-11e7-9653-54e0137e53ae.png)

**Comment by singingwolfboy** [comment]
@blarghmatey and I got this figured out, and it's working now.

**Comment by pdpinch** [comment]
I'm reopening this because, as far as I know, the Moira authorization isn't in place yet.

**Comment by singingwolfboy** [comment]
Moira authorization is now in place.
