### ISSUE TITLE
Allow collection admins to delete videos

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#202]
Currently the only way to delete videos  is through the django admin console.  Collection administrators should be able to delete videos (and collections) through the standard front-end.

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/30491341-ff277436-9a0a-11e7-88e6-cb5aecb2ee79.png)

![image](https://user-images.githubusercontent.com/20047260/30491320-ee76d262-9a0a-11e7-93e0-e6d86a7e3b8a.png)

![image](https://user-images.githubusercontent.com/20047260/30491505-7f1f35a2-9a0b-11e7-9cbc-4221408f1a28.png)

Here is a design for the Delete Video ux for Admins only. Clicking on the Delete button will open a confirmation dialog. After confirming, we should redirect to the Collection page and show a toast message confirming that the video has been deleted.

**Comment by roberthouse54** [comment]
Also, just a note... as I think we will be adding more buttons to the page (delete and download), I think we should make the buttons smaller as shown.

**Comment by roberthouse54** [comment]
Also, we should add a delete icon to the Collection Detail page. This will allow admins to delete Videos that error and fail to upload.

![image](https://user-images.githubusercontent.com/20047260/30491813-803df580-9a0c-11e7-9476-c404359804a1.png)

**Comment by pdpinch** [comment]
Update the description to make it clearer that this applies to deleting video only. 

If we want to allow collection admins to delete a collection, we can open a separate issue for that.

**Comment by gsidebo** [comment]
@roberthouse54 is going to revise these designs. Setting the issue to blocked for now

**Comment by roberthouse54** [comment]
I have deleted the mocks I had on here previously. I will upload new mocks for this feature.

**Comment by roberthouse54** [comment]
The delete feature is available to admins only. We will add a Delete button to the Video Details page, same style as existing buttons. Clicking the button will open a delete confirmation modal. After deleting a video the user will be directed to the collection details page, where we will show a toast message confirming that the video has been deleted. In the video card, we will get rid of the existing icons, and replace them with a material design "overflow menu". This will contain the three links to "Edit" "Share" and "Delete". We will also make it so that the user can click on videos that failed to transcode or upload, and go to the video details page, displaying a broken or missing video.

![image](https://user-images.githubusercontent.com/20047260/30936618-76f8be2a-a3a2-11e7-963e-337bf0ebbe27.png)

![image](https://user-images.githubusercontent.com/20047260/30936643-86b650c0-a3a2-11e7-9840-7d5d29d21c88.png)

![image](https://user-images.githubusercontent.com/20047260/30936850-17e73e9c-a3a3-11e7-88df-49a6a15f1378.png)

**Comment by gsidebo** [comment]
@roberthouse54 FYI we don't keep the original filename around after uploading, so we probably want to rethink the contents of the delete confirmation dialog

**Comment by roberthouse54** [comment]
OK, how about we show the video title in the modal instead of the filename?
