### ISSUE TITLE
Create a Collection button on drawer doesn't work if on video detail page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#374]

**Comment by adorsk** [comment]
This issue is somewhat problematic.

The reason why the "Create collection" button doesn't work on the VideoDetail page is that `VideoDetailPage` does not include`CollectionFormDialog`.

However, simply including `CollectionFormDialog` in `VideoDetailPage` raises another issue: what should happen after a collection is created from the VideoDetail page? Should we (a) immediately navigate to the new collection? Or (b) should we stay on the VideoDetail page? Or (c) something else?

(a) & (b) both seem weird to me. Which makes me think we should *not* be able to create collections from the VideoDetail page.

A few options are:

### 1. Remove the "Create collection" button entirely from the drawer

#### Pros:
1. Simplifies drawer.
2. Avoids confusing navigation issues raised above.
3. Makes the drawer a purely navigational component, rather than a hybrid navigation/tool component.

#### Cons:
1. Only place to create collection is from the `/collections` page. (this may actually be good).

We could remove the button entirely, or replace it with a link to the `/collections` page.

### 2. Hide the button just for the VideoDetail page.

#### Pros:
1. Avoids confusing navigation issues raised above.

#### Cons:
1. Complicates drawer.
2. Drawer is still a hybrid tool/navigation component.

### 3. Something else.

IMHO, we should go with 1. (Remove 'Create Collections' button entirely). Creating collections should be a relatively rare event, and I think it's better to do it from one spot, the `/collections` page.

**Comment by pdpinch** [comment]
Ok, let’s just remove the button.
