### ISSUE TITLE
Allow video, thumbnails, captions to come from multiple S3 buckets

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#412]

**Comment by mbertrand** [comment]
- Cloudfront URL's need to be mapped to S3 buckets (devops) - part of #411?  For example:

<img width="483" alt="screen shot 2018-01-23 at 3 54 04 pm" src="https://user-images.githubusercontent.com/187676/35300186-bc67b348-0055-11e8-8afa-ddc014e3ef37.png">


- S3 keys for TechTV videos, thumbnails, captions need to be assigned with a techtv prefix, for example `techtv/thumbnails/9d6aa5cf9b6e4d07a0dfdcd9aaf633f0/video_thumbnail_00001.jpg` instead of `thumbnails/9d6aa5cf9b6e4d07a0dfdcd9aaf633f0/video_thumbnail_00001.jpg` (via code)

**Comment by pdpinch** [comment]
I think the mapping of S3 to cloudfront is part of #411 -- please add a comment and/or edit the description. 

This issue was for any necessary data model and front-end changes.

**Comment by mbertrand** [comment]
Each `VideoS3` object (used for video files, thumbnails, and captions) has a `bucket_name` and `s3_object_key` property.  These can be set to the appropriate TechTV bucket and path when creating an object, for example:
```python
VideoThumbnail.objects.get_or_create(
     s3_object_key='techtv/thumbnails/001.jpg,
     bucket_name='odl-video-services-techtv-thumbnails-ci'
     video=video
)
```
Each cloudfront URL is based on the S3 object key, so assuming the cloudfront distribution maps unique URL paths for techtv files to S3 buckets, everything should just work.

A complication is that each `VideoFile` is assumed to be either the original uploaded file or an m3u8 playlist of transcoded files, which won't be the case for TechTV videos.  That will be addressed as part of #413.

**Comment by pdpinch** [comment]
Does that mean we can just close this?

**Comment by mbertrand** [comment]
Yes, I'll close it.
