### ISSUE TITLE
modify video.js player to support mp4 videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#413]

**Comment by mbertrand** [comment]
- The `VideoFile` for a TechTV video should be a sources list in JSON format instead of an m3u8 HLS playlist:
    ```
    [
      {
        src: 'https://sdfsf.cloudfront.net/techtv/../small.mp4',
        type: 'video/mp4',
        label: '360',
        res: 360
      },
      {
        src: 'https://sdfsf.cloudfront.net/techtv/../medium.mp4',
        type: 'video/mp4',
        label: '720',
        res: 720
      }
    ]
    ```
- Add `MP4` to `encodings.EncodingNames` and use that for the `VideoFile` encoding.
- Use the [videojs resolution switcher plugin](https://github.com/kmoskwiak/videojs-resolution-switcher) to allow manual selection of resolution (unfortunately it will not autoselect based on bandwidth).
- Modify the React `VideoPlayer` component to load the appropriate plugins and configuration based on the encoding.

**Comment by mbertrand** [comment]
@pdpinch the VideoJS resolution switcher plugin won't automatically select the best resolution for the available bandwidth, unlike the HLS plugin.  But it gives the option of setting either the lowest resolution or the highest as the default.  Do you have a preference?

**Comment by emmello** [comment]
I would do highest and let it downspeed for lower connections.
