### ISSUE TITLE
display an error in the front-end when API calls fail

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#463]
On the collection page, when the API call to list video fails, we display the misleading message: "You have not added any videos yet"

Instead, we should:

- [ ] raise an exception to Sentry
- [ ] display an error along the lines of "Sorry, we were unable to load the data necessary to process your request. Please reload the page. If this happens again, please contact `<support email>`"

**Comment by pdpinch** [comment]
@roberthouse54 Should we use a toast message for this?

can you give me a 2nd opinion on the text of the error message?

**Comment by roberthouse54** [comment]
I think we could go with something like:

"Oops, something went wrong. We were not able to load the page. Please refresh the page. If this happens again, please contact <support email>."

I think a toast message could work.

**Comment by adorsk** [comment]
This is how I'm interpreting the expected behavior, based on above comments:

### Case 1: error unrelated to permissions
1. log sentry exception
2. render this message: "Sorry, we were unable to load the data necessary to process your request. Please reload the page. If this happens again, please contact <support email>"

### Case 2: error related to permissions
1. Render this message: "You don't have permissions to view this collection."

**Comment by adorsk** [comment]
#570 and #571 have been merged and close this issue.

**Comment by adorsk** [comment]
Correction, still waiting on #571

**Comment by adorsk** [comment]
#571 finished, closing here.
