### ISSUE TITLE
`collectstatic` puts files in wrong directory when OVS is deployed via Salt

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#467]
The Salt deployment of OVS to production causes the static files to be copied to `/home/deploy` which is not the correct folder for the app, because the `STATIC_ROOT` setting is relative.

**Comment by blarghmatey** [comment]
The issue arises because of the fact that the `STATIC_ROOT` setting is a relative path, so it will change based on the current working directory of whichever user/process is executing the `collectstatic` management command. By changing the static root to be a fully qualified path we can avoid issues with inconsistent command execution putting the static assets in the wrong location, reducing the amount of extra effort necessary to ensure consistent deployments.
