### ISSUE TITLE
Add the OVS instance as a `user metadata` key-value for pipeline jobs

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#483]
Add the instance (CI, RC, production) sending a transcode job to AWS as a `User metadata` key-value pair for each job, for example:
```
instance: ci
instance: rc
instance: prod
```

**Comment by pdpinch** [comment]
Can we align this with the "environment" set in Sentry?

**Comment by shaidar** [comment]
Just to give this some context, there currently is no way to tag AWS ElasticTranscode Pipelines. Hence, it's difficult to determine cost if there are multiple apps utilizing that service. One recommended way to get around that problem is to add a `key:value` to the job itself and use that to filter on the billing side.
Given that we probably should be specifying the name of the app, in addition to the environment as such:
```
pipeline: odl-video-service-ci
pipeline:odl-video-service-rc
pipeline:odl-video-service-prod
```

**Comment by mbertrand** [comment]
Looks like this can be done by overriding the `Transcoder.encode` method in child class `cloudsync.utils.VideoTranscoder` to add the `UserMetadata` section to the job request.
