### ISSUE TITLE
cc support email when sending a processing failed email 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#552]
The email that we send when video processing fails says that the ODL Engineering team will be alerted. This is true, to the extent that we should get an issue raised in Sentry. However, it can be hard to match the Sentry error to the specific video. 

We should cc the support e-mail address (i.e. ZenDesk) when we send error emails, which will create a ticket. 

Unfortunately, this is not as simple as making a change to the mail template.

**Comment by adorsk** [comment]
@pdpinch How much do we care about `cc`'ing the support email address, as opposed to just adding the support email address as another plain recipient?

To clarify:

### A. With CC:
With `cc`-ing, the email to the video uploader would look like this:
```
From: odl-video-service
To: person-who-uploaded
cc: support@video
```

### B. Without `CC`-ing, Using Plain Recipient Instead:
Without `cc`-ing, the email to the video uploader would look like this:
```
From: odl-video-service
To: person-who-uploaded, support@video
```

I ask because B is much faster to implement than A. (Probably 1-2 hours vs. 6-8).

Is it necessary to do A?

**Comment by adorsk** [comment]
ah, nevermind, upon digging deeper I think I have to pursue the implementation path of B in any case.

So, proper CC's it shall be.

**Comment by pdpinch** [comment]
Sounds like this is moot but, for the record, either is fine.

**Comment by adorsk** [comment]
Just realized a better solution (imho) is just to send an entirely separate email to support. This avoids complications of recipient types, and allows us to put extra debugging info the email to support.
So that's the path I'll pursue.
