### ISSUE TITLE
Show errors in UI

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#57]
We should consider these cases in general:
 - configuration error
 - error uploading to dropbox
 - dropbox to amazon processing error
 - validation errors when creating or editing video description #47 #48 
 - transcode error
 - connectivity errors regarding video
 - out of space on cloud services

**Comment by mbertrand** [comment]
@noisecapella @giocalitri @pdpinch Here's the approach I'm thinking of taking for 'dropbox to amazon processing' errors or transcode errors (both celery tasks), and for configuration problems that cause these tasks to fail:

- Log all exceptions (and then raise them) that occur during celery upload/transcode tasks so Sentry will pick them up and devops will be notified.  One unresolved issue: if there is some kind of code syntax error in the celery task that prevents it from even starting, there does not seem to be any record of it in logs, it just fails silently.
- Add 'error_raw' and 'error_message' fields to the Video model.  'error_raw' will contain the literal error message, such as:
  - `4000 f5c7bdf7-0776-4a0b-bbb0-922cb3b1ee67: Amazon Elastic Transcoder could not interpret the media file.`
and the error_message is what will be displayed to the user:
  - `The video file could not be processed.  It may be corrupt or in an incompatible format.`

For validation errors (https://github.com/mitodl/odl-video-service/issues/47 https://github.com/mitodl/odl-video-service/issues/48): Make the video title field mandatory (non-blankable/non-nullable), make moira_list optional.  Display appropriate error message on validation errors in the UI ('Please enter a title').

Video connectivity issues:  The video.js player will display an error if the video cannot be played but it is not that user-friendly.  I will have to do some research to find out if it can be customized.

- Error uploading to dropbox: Not part of the app, so out of scope.
- Out of space on cloud services: I don't think this should ever happen unless there's some kind of massive S3 service failure, but if for some reason files cannot be written to or read from S3/Cloudfront it should be handled by one of the above use cases.

**Comment by mbertrand** [comment]
For related issue https://github.com/mitodl/odl-video-service/issues/63: For each video on the video list page, display it's status ('Uploading', 'Transcode Failed', etc) next to the title if it is not complete, otherwise just show the title.

**Comment by mbertrand** [comment]
Video.js plugin for user-friendly errors, with localization: https://github.com/brightcove/videojs-errors

**Comment by mbertrand** [comment]
- configuration error
Default to values that raise exceptions if not present? Then create a management command to test the settings actually work?

 - error uploading to dropbox
This is not our problem

 - dropbox to amazon processing error
There are 2 parts of the problem: 
1- us as devs being notified (and this will happen via Sentry)
2- the user needs to be notified: if the upload fails we sett the status of the video object to "upload failed" so that it can be retrieved. The notication should be user-friendly: #70

 - validation errors when creating or editing video description #47 #48 
We solve by not allowing problematic values
We will make Mora List optional for the time being

 - transcode error
Same way as we  handle upload

 - connectivity errors regarding video
We need to look in the vide players and how to handle that  #71

 - out of space on cloud services
I do not think we need to worry about this

- we need to handle all the cases when AWS or Dropbox is not reachable (or both)

**Comment by pdpinch** [comment]
I believe we've covered all these issues now.
