### ISSUE TITLE
Download links for public videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#639]
As a Blossoms user, I'd like to be able to download videos using original TechTV URLs.

**Comment by pdpinch** [comment]
This will require some initial research into the structure of the old TechTV URLs. 

We will also need to decide if we will still return some of the outdated formats, like QuickTime.

**Comment by emmello** [comment]
The quicktime videos probably predate AWS.  Since TTV moved, the options for download were mp4.  Some older links had "original" but newer ones allowed a basic video download along with a higher res option.   

One example of how it looked is on the right hand margin here:    
![image](https://user-images.githubusercontent.com/1099800/40366088-451e8c9c-5da4-11e8-9429-ebc5cafbd0ba.png)

**Comment by pdpinch** [comment]
@emmello is going to recommend to Blossoms that they download the video into their dropbox and share it.

**Comment by pdpinch** [comment]
We discussed further with the Blossom folks and our plan is to support two download URL patterns:

old techtv links: 

http://techtv.mit.edu/videos/[VIDEO ID]/download.mp4 (any extension should return the same mp4 file)

new OVS videos:

https://video.odl.mit.edu/videos/[VIDEO KEY]/download

We should also test the links with the Blossoms implementation, which appears to proxy the download URL through their web application.

**Comment by mbertrand** [comment]
This should only work for public videos, right?  Return a 404 if someone tries a download link for a non-public video?
