### ISSUE TITLE
batch re-encode HLS video

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#788]
As an admin, I'd like an easy, scalable way to re-encode videos for some collections, especially when we add or change the encoding presets (see #787). 

#### Acceptance criteria

- [ ] option for re-encoding just one video, by ID
- [ ] option for re-encoding all videos in a collection, by collection ID (or collection name?)
- [ ] after the video is re-encoded, need a way to discard the old encodings

#### out of scope

- I think it's best not to have an option to re-encode all the videos on the site, since that is a expensive undertaking

**Comment by mbertrand** [comment]
Do you want a management command?  devops would need to run it since RC and PR are not on heroku.  

Or I could add a boolean 'schedule_encode' field on both Video and Collection objects, and set up a recurring celery task to reencode any of those objects with `schedule_encode=True` (and then set that to False again).

`after the video is re-encoded, need a way to discard the old encodings` - I think we are just adding additional encodings?  The m3u8 file for a video will regenerated too and any unused encodings won't be in it.

**Comment by pdpinch** [comment]
I like the idea of adding the "schedule_encode" field. Can we add that as a filter in the admin so there's a way to find collections and videos that are in one state or the other?

In the interests of time, we may only be adding new encoding now, but I'd like to have an option to replace existing encodings with entirely new ones.

**Comment by mbertrand** [comment]
@pdpinch Unfortunately there's a complication: Elastic Transcoder will not overwrite existing files, so a retranscode will always fail (`The specified object could not be saved in the specified bucket because an object by that name already exists`).  Some possible workarounds:

- Rewrite the code to specify temporary s3 bucket files for ET to write to, and when finished copy to the correct S3 location and delete the temporary ones.
- Remove the original transcode files before retranscoding.  This is obviously not ideal because then the video will be unplayable until the retranscode is complete.

**Comment by mbertrand** [comment]
Here is the proposed approach:

- Create a flag on Collection and Video: boolean field ‘schedule_reencode’
- Create a recurring task to look for videos and collections with schedule_reencode=True.
  - check flagged collections first:
     - set flag to True for every video in the collection
     - reset collection flag to False
  - Trigger a new encode job for each flagged video.
  - Assign new video status - ‘Re-encoding’ 
  - Reset flag to False
- Modify the existing encoding job metadata:
  - a temporary prefix should be added to the output filenames to avoid transcode errors that occur when trying to overwrite existing output from the previous transcode
- Videos being retranscoded should still be playable (front end needs to accept reencoding status as playable)
- Modify task that checks on video transcode status 
  - should handle the new reencoding status
- There will now be 2+ encode jobs for the video instead of just 1, the most recent is the one that needs to be checked for progress.
- When a reencoding is complete: 
  - copy output from the temporary S3 subfolder to the correct subfolder, then delete the temporary files
  - Change video status back to complete
- If a reencoding task fails:
  - Log the error
  - Set video status back to complete (original transcode should still work)

**Comment by pdpinch** [comment]
At a high level, this sounds right, but I think there are some details that need attention — like when and how to update the “re-encoding” status. 

Do you want to open an RFC PR with this description?

I think it’s safe enough, and urgent enough, that you get started. But I want to make sure we capture the decisions you’re making now. 

@gsidebo do you want to weigh in?

**Comment by mbertrand** [comment]
@pdpinch here is the RFC: https://github.com/mitodl/odl-video-service/pull/791

**Comment by mbertrand** [comment]
@pdpinch another question, should the email 'Video X in Collection Y done processing' go out again after a retranscode?

**Comment by gsidebo** [comment]
I'm wondering if it makes more sense just to add an option to re-transcode in the UI. If I'm not mistaken, both collections and videos have dot menus that we could add options to. It seems like it would require minimal front end code to get that working

**Comment by pdpinch** [comment]
> @pdpinch another question, should the email 'Video X in Collection Y done processing' go out again after a retranscode?

Whatever is easier is fine. We don't need emails, but I don't think anyone would mind them either. 

> I'm wondering if it makes more sense just to add an option to re-transcode in the UI. If I'm not mistaken, both collections and videos have dot menus that we could add options to. It seems like it would require minimal front end code to get that working

I don't think the re-encode option is going to be intelligible to the collection owner. I'm hoping (naively) that this is a one-time event for the collection that need re-encoding. Future collections after the preset change should just use the new preset.

**Comment by gsidebo** [comment]
If we're expecting this to be a one-time event, then at the very least we should feature flag this so we can prevent a situation where we have a permanently-running celery task checking for videos/collections that have this re-encode flag set

**Comment by mbertrand** [comment]
A preliminary PR is up (still needs tests) and I added a feature flag, thanks for the suggestion @gsidebo .  There's also an RFC PR.
